(() => {
  "use strict";

  const LABS = [
    {id:"image",route:"lab-image",no:"01",title:"IMAGE STUDIO",status:"LIVE EXPERIMENT",copy:"Frame, clean and export visual assets.",preview:'<div class="lab-mini-image"></div>'},
    {id:"motion",route:"lab-motion",no:"02",title:"MOTION LAB",status:"LIVE EXPERIMENT",copy:"Compare timing, easing and motion feel.",preview:'<div class="lab-mini-track"></div><div class="lab-mini-motion"></div>'},
    {id:"spatial",route:"lab-spatial",no:"03",title:"SPATIAL UI LAB",status:"LIVE EXPERIMENT",copy:"Place interfaces across depth and focus.",preview:'<div class="lab-mini-space"><i></i><i></i><i></i></div>'},
    {id:"interaction",route:"lab-interaction",no:"04",title:"INTERACTION PLAYGROUND",status:"LIVE EXPERIMENT",copy:"Test how one object responds to input.",preview:'<div class="lab-mini-magnet">MOVE CLOSER</div>'},
    {id:"material",route:"lab-material",no:"05",title:"MATERIAL LAB",status:"EXPERIMENT",copy:"Shape glass, glow and digital surfaces.",preview:'<div class="lab-mini-material"></div>'},
    {id:"generative",route:"lab-generative",no:"06",title:"GENERATIVE PLAYGROUND",status:"EXPERIMENT",copy:"Guide small systems through force and flow.",preview:'<canvas class="lab-mini-canvas" aria-hidden="true"></canvas>'}
  ];

  const reduce = matchMedia("(prefers-reduced-motion: reduce)").matches;
  const fine = matchMedia("(pointer:fine)").matches;
  const clamp = (value,min,max) => Math.max(min,Math.min(max,value));
  const $ = (root,selector) => root.querySelector(selector);
  const $$ = (root,selector) => [...root.querySelectorAll(selector)];
  const setCursorState = value => {
    const cursor=document.querySelector(".cursor");
    if(!cursor) return;
    if(value) cursor.dataset.labState=value;
    else delete cursor.dataset.labState;
  };
  let toastTimer=0;
  const toast = message => {
    let node=document.querySelector(".lab-toast");
    if(!node){node=document.createElement("div");node.className="lab-toast";node.setAttribute("role","status");document.body.append(node)}
    node.textContent=message;
    node.classList.add("is-visible");
    clearTimeout(toastTimer);
    toastTimer=setTimeout(()=>node.classList.remove("is-visible"),1100);
  };
  const copyText = async text => {
    try{await navigator.clipboard.writeText(text)}catch{
      const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand("copy");area.remove();
    }
    toast("COPIED");
  };
  const savePreset = (key,value) => {
    try{localStorage.setItem(`yuYouLab.${key}`,JSON.stringify(value));toast("PRESET SAVED")}catch{toast("SAVE UNAVAILABLE")}
  };
  const readPreset = key => {
    try{return JSON.parse(localStorage.getItem(`yuYouLab.${key}`)||"null")}catch{return null}
  };
  const rangeField = (id,label,min,max,value,step=1,suffix="") => `<div class="lab-field"><div class="lab-field-row"><label for="${id}">${label}</label><output class="lab-value" for="${id}" data-output="${id}">${value}${suffix}</output></div><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></div>`;
  const segment = (value,label,active=false) => `<button class="lab-segment${active?" is-active":""}" type="button" data-value="${value}">${label}</button>`;
  const bindRangeOutputs = root => {
    $$ (root,'input[type="range"]').forEach(input=>{
      const output=root.querySelector(`[data-output="${input.id}"]`);
      if(!output) return;
      const suffix=output.textContent.replace(/^[-.\d]+/,"");
      input.addEventListener("input",()=>{output.textContent=`${input.value}${suffix}`});
    });
  };
  const shell = (mount,{number,title,copy,stageClass,stage,controls}) => {
    mount.innerHTML=`<div class="lab-shell"><div class="lab-topbar"><div class="lab-topbar-copy"><a class="lab-back interactive" href="#lab">&larr; BACK TO LAB</a><span class="label">${number} · LIVE EXPERIMENT</span><h1 tabindex="-1">${title}</h1></div><p>${copy}</p></div><div class="lab-layout"><div class="lab-stage ${stageClass}">${stage}</div><aside class="lab-controls" aria-label="${title} controls"><button class="lab-controls-toggle" type="button" aria-expanded="true"><span>CONTROLS</span><span>−</span></button><div class="lab-controls-body">${controls}</div></aside></div></div>`;
    const panel=$(mount,".lab-controls");
    const toggle=$(mount,".lab-controls-toggle");
    toggle.addEventListener("click",()=>{const collapsed=panel.classList.toggle("is-collapsed");toggle.setAttribute("aria-expanded",String(!collapsed));toggle.lastElementChild.textContent=collapsed?"+":"−"});
    bindRangeOutputs(mount);
    requestAnimationFrame(()=>$(mount,"h1")?.focus({preventScroll:true}));
    return {stage:$(mount,".lab-stage"),controls:panel};
  };

  function renderIndex(){
    const grid=document.getElementById("labIndexGrid");
    if(!grid) return;
    grid.innerHTML=LABS.map(lab=>`<a class="lab-card interactive" href="#${lab.route}" data-lab-card="${lab.id}"><div class="lab-card-preview">${lab.preview}</div><div class="lab-card-copy"><div class="lab-card-meta"><span>${lab.no}</span><span>${lab.status}</span></div><h3>${lab.title}</h3><p>${lab.copy}</p></div></a>`).join("");
    const canvas=$(grid,".lab-mini-canvas");
    if(canvas){
      const draw=(x=.5,y=.5)=>{const rect=canvas.getBoundingClientRect();canvas.width=Math.max(1,rect.width*devicePixelRatio);canvas.height=Math.max(1,rect.height*devicePixelRatio);const ctx=canvas.getContext("2d");ctx.scale(devicePixelRatio,devicePixelRatio);for(let i=0;i<28;i++){const px=(i*47%100)/100*rect.width,py=(i*73%100)/100*rect.height;const d=Math.hypot(px-x*rect.width,py-y*rect.height);ctx.fillStyle=i%3===0?"#ff62b0":i%3===1?"#916cff":"#00bdb6";ctx.globalAlpha=clamp(1-d/210,.16,.8);ctx.beginPath();ctx.arc(px,py,2+(i%4),0,Math.PI*2);ctx.fill()}};
      requestAnimationFrame(()=>draw());
      canvas.closest(".lab-card")?.addEventListener("pointermove",event=>{const r=canvas.getBoundingClientRect();draw((event.clientX-r.left)/r.width,(event.clientY-r.top)/r.height)});
    }
  }

  function createImageLab(mount){
    const defaults={size:"1200x630",fit:"contain",background:"gradient",colorA:"#ffe6f0",colorB:"#dff5ff",angle:135,shadow:"floating",corner:"medium",padding:72,replaceWhite:true,tolerance:38,frame:"portfolio"};
    const state={...defaults,...(readPreset("image")||{}),image:null,processed:null};
    shell(mount,{number:"01",title:"IMAGE STUDIO",copy:"Prepare portfolio and social imagery with immediate, canvas-based feedback.",stageClass:"image-studio-stage",stage:'<span class="frame-badge">PORTFOLIO FRAME</span><canvas id="labImageCanvas" width="1200" height="630" aria-label="Image Studio preview"></canvas>',controls:`
      <div class="lab-control-group"><span class="lab-control-title">SOURCE</span><div class="lab-field"><label for="labImageUpload">UPLOAD IMAGE</label><input id="labImageUpload" type="file" accept="image/*"></div><div class="lab-field"><label for="labImageFit">FIT</label><select id="labImageFit"><option value="contain">CONTAIN</option><option value="cover">COVER</option></select></div><label class="toggle-row"><input id="labImageWhite" type="checkbox"> REPLACE EDGE-CONNECTED WHITE</label>${rangeField("labImageTolerance","TOLERANCE",0,90,state.tolerance)}</div>
      <div class="lab-control-group"><span class="lab-control-title">ASPECT PRESETS</span><div class="lab-segments" data-segments="size">${[["1080x1080","1:1"],["1080x1350","4:5"],["1600x900","16:9"],["1080x1920","9:16"],["1200x630","1200×630"]].map(([v,l])=>segment(v,l,v===state.size)).join("")}</div><div class="lab-field-row"><div class="lab-field"><label for="labImageCustomW">CUSTOM W</label><input id="labImageCustomW" type="number" min="320" max="2400" value="1200"></div><div class="lab-field"><label for="labImageCustomH">CUSTOM H</label><input id="labImageCustomH" type="number" min="320" max="2400" value="900"></div></div><button class="lab-action" data-action="custom" type="button">APPLY CUSTOM</button></div>
      <div class="lab-control-group"><span class="lab-control-title">BACKGROUND</span><div class="lab-segments" data-segments="background">${["solid","gradient","transparent"].map(v=>segment(v,v.toUpperCase(),v===state.background)).join("")}</div><div class="lab-field-row"><label for="labImageA">COLOR A</label><input id="labImageA" type="color" value="${state.colorA}"><label for="labImageB">COLOR B</label><input id="labImageB" type="color" value="${state.colorB}"></div>${rangeField("labImageAngle","GRADIENT ANGLE",0,360,state.angle,1,"°")}</div>
      <div class="lab-control-group"><span class="lab-control-title">FRAME</span><div class="lab-field"><label for="labImageFrame">PREVIEW</label><select id="labImageFrame"><option value="portfolio">PORTFOLIO</option><option value="instagram">INSTAGRAM</option><option value="story">STORY</option><option value="og">OG IMAGE</option></select></div><div class="lab-field"><label for="labImageShadow">SHADOW</label><select id="labImageShadow"><option value="none">NONE</option><option value="soft">SOFT</option><option value="floating">FLOATING</option></select></div><div class="lab-field"><label for="labImageCorner">CORNER</label><select id="labImageCorner"><option value="square">SQUARE</option><option value="small">SMALL</option><option value="medium">MEDIUM</option><option value="large">LARGE</option></select></div>${rangeField("labImagePadding","PADDING",0,240,state.padding,1," px")}</div>
      <div class="lab-control-group"><div class="lab-actions"><button class="lab-action primary" data-action="png" type="button">DOWNLOAD PNG</button><button class="lab-action" data-action="webp" type="button">DOWNLOAD WEBP</button><button class="lab-action" data-action="save" type="button">SAVE PRESET</button><button class="lab-action" data-action="reset" type="button">RESET</button></div></div>`});
    const canvas=$(mount,"#labImageCanvas"),ctx=canvas.getContext("2d"),badge=$(mount,".frame-badge");
    const cornerMap={square:0,small:24,medium:64,large:120};
    const rounded=(x,y,w,h,r)=>{r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.roundRect(x,y,w,h,r)};
    const prepareImage=()=>{
      if(!state.image) return null;
      if(state.processed) return state.processed;
      const max=2048,scale=Math.min(1,max/Math.max(state.image.naturalWidth,state.image.naturalHeight));
      const source=document.createElement("canvas");source.width=Math.round(state.image.naturalWidth*scale);source.height=Math.round(state.image.naturalHeight*scale);
      const sx=source.getContext("2d",{willReadFrequently:true});sx.drawImage(state.image,0,0,source.width,source.height);
      if(state.replaceWhite){
        const imageData=sx.getImageData(0,0,source.width,source.height),data=imageData.data,min=255-state.tolerance,seen=new Uint8Array(source.width*source.height),queue=[];
        const white=i=>{const o=i*4,r=data[o],g=data[o+1],b=data[o+2];return data[o+3]>0&&r>=min&&g>=min&&b>=min&&Math.max(r,g,b)-Math.min(r,g,b)<=state.tolerance};
        const push=i=>{if(i>=0&&i<seen.length&&!seen[i]&&white(i)){seen[i]=1;queue.push(i)}};
        for(let x=0;x<source.width;x++){push(x);push((source.height-1)*source.width+x)}for(let y=0;y<source.height;y++){push(y*source.width);push(y*source.width+source.width-1)}
        for(let q=0;q<queue.length;q++){const i=queue[q],o=i*4,x=i%source.width,y=Math.floor(i/source.width);data[o+3]=0;if(x)push(i-1);if(x<source.width-1)push(i+1);if(y)push(i-source.width);if(y<source.height-1)push(i+source.width)}
        sx.putImageData(imageData,0,0);
      }
      state.processed=source;return source;
    };
    const drawDemo=()=>{const w=canvas.width,h=canvas.height;ctx.save();ctx.translate(w/2,h/2);ctx.rotate(-.08);const dw=w*.46,dh=h*.5;const grad=ctx.createLinearGradient(-dw/2,-dh/2,dw/2,dh/2);grad.addColorStop(0,"#ff62b0");grad.addColorStop(.5,"#916cff");grad.addColorStop(1,"#00bdb6");ctx.fillStyle=grad;ctx.shadowColor="rgba(68,52,101,.22)";ctx.shadowBlur=45;rounded(-dw/2,-dh/2,dw,dh,cornerMap[state.corner]);ctx.fill();ctx.shadowColor="transparent";ctx.strokeStyle="rgba(255,255,255,.66)";ctx.lineWidth=2;rounded(-dw/2+24,-dh/2+24,dw-48,dh-48,Math.max(8,cornerMap[state.corner]-18));ctx.stroke();ctx.fillStyle="#fff";ctx.font=`600 ${Math.max(24,w*.035)}px Space Grotesk`;ctx.textAlign="center";ctx.fillText("DROP YOUR IMAGE",0,8);ctx.font=`500 ${Math.max(11,w*.012)}px DM Sans`;ctx.fillText("LIVE CANVAS PREVIEW",0,42);ctx.restore()};
    const draw=()=>{
      const [w,h]=state.size.split("x").map(Number);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.clearRect(0,0,w,h);
      if(state.background!=="transparent"){if(state.background==="gradient"){const rad=state.angle*Math.PI/180,x=Math.cos(rad)*w/2,y=Math.sin(rad)*h/2,g=ctx.createLinearGradient(w/2-x,h/2-y,w/2+x,h/2+y);g.addColorStop(0,state.colorA);g.addColorStop(1,state.colorB);ctx.fillStyle=g}else ctx.fillStyle=state.colorA;ctx.fillRect(0,0,w,h)}
      const image=prepareImage();if(!image){drawDemo();return}
      const areaW=Math.max(1,w-state.padding*2),areaH=Math.max(1,h-state.padding*2),scale=state.fit==="cover"?Math.max(areaW/image.width,areaH/image.height):Math.min(areaW/image.width,areaH/image.height),dw=image.width*scale,dh=image.height*scale,dx=(w-dw)/2,dy=(h-dh)/2,r=cornerMap[state.corner];
      ctx.save();if(state.shadow!=="none"){ctx.shadowColor=state.shadow==="soft"?"rgba(68,52,101,.18)":"rgba(68,52,101,.3)";ctx.shadowBlur=state.shadow==="soft"?28:64;ctx.shadowOffsetY=state.shadow==="soft"?12:28}rounded(dx,dy,dw,dh,r);ctx.clip();ctx.drawImage(image,dx,dy,dw,dh);ctx.restore();
    };
    const sync=()=>{$(mount,"#labImageFit").value=state.fit;$(mount,"#labImageWhite").checked=state.replaceWhite;$(mount,"#labImageTolerance").value=state.tolerance;$(mount,"#labImageA").value=state.colorA;$(mount,"#labImageB").value=state.colorB;$(mount,"#labImageAngle").value=state.angle;$(mount,"#labImageFrame").value=state.frame;$(mount,"#labImageShadow").value=state.shadow;$(mount,"#labImageCorner").value=state.corner;$(mount,"#labImagePadding").value=state.padding;$$ (mount,"[data-segments]").forEach(group=>$$ (group,"button").forEach(button=>button.classList.toggle("is-active",state[group.dataset.segments]===button.dataset.value)));badge.textContent=`${state.frame.toUpperCase()} FRAME`;draw()};
    $(mount,"#labImageUpload").addEventListener("change",event=>{const file=event.target.files[0];if(!file)return;const image=new Image();image.onload=()=>{state.image=image;state.processed=null;draw()};image.src=URL.createObjectURL(file)});
    mount.addEventListener("input",event=>{const map={labImageFit:"fit",labImageWhite:"replaceWhite",labImageTolerance:"tolerance",labImageA:"colorA",labImageB:"colorB",labImageAngle:"angle",labImageFrame:"frame",labImageShadow:"shadow",labImageCorner:"corner",labImagePadding:"padding"},key=map[event.target.id];if(!key)return;state[key]=event.target.type==="checkbox"?event.target.checked:event.target.type==="range"?Number(event.target.value):event.target.value;if(key==="replaceWhite"||key==="tolerance")state.processed=null;badge.textContent=`${state.frame.toUpperCase()} FRAME`;draw()});
    $$ (mount,"[data-segments] button").forEach(button=>button.addEventListener("click",()=>{const group=button.closest("[data-segments]");state[group.dataset.segments]=button.dataset.value;$$ (group,"button").forEach(item=>item.classList.toggle("is-active",item===button));draw()}));
    mount.addEventListener("click",event=>{const action=event.target.dataset.action;if(!action)return;if(action==="reset"){Object.assign(state,defaults,{image:null,processed:null});$(mount,"#labImageUpload").value="";sync()}if(action==="custom"){const w=clamp(Number($(mount,"#labImageCustomW").value)||1200,320,2400),h=clamp(Number($(mount,"#labImageCustomH").value)||900,320,2400);state.size=`${w}x${h}`;$$ (mount,"[data-segments='size'] button").forEach(button=>button.classList.remove("is-active"));draw()}if(action==="save")savePreset("image",Object.fromEntries(Object.entries(state).filter(([k])=>!["image","processed"].includes(k))));if(action==="png"||action==="webp"){const link=document.createElement("a");link.download=`yu-you-image-studio.${action}`;link.href=canvas.toDataURL(`image/${action}`,.92);link.click()}});
    sync();return ()=>{};
  }

  function createMotionLab(mount){
    const easings={linear:"linear",ease:"ease",in:"ease-in",out:"ease-out",inout:"ease-in-out",spring:"cubic-bezier(.18,.9,.28,1.28)",bounce:"cubic-bezier(.34,1.56,.64,1)",overshoot:"cubic-bezier(.2,1.35,.35,1)",soft:"cubic-bezier(.22,.65,.3,1)",snappy:"cubic-bezier(.2,.9,.2,1)",smooth:"cubic-bezier(.4,0,.2,1)"};
    const defaults={shape:"card",duration:850,delay:0,distance:420,scale:1.08,rotation:8,opacity:.72,easing:"out",compare:false,left:"out",right:"spring",x1:.22,y1:.65,x2:.3,y2:1,stiffness:180,damping:18,mass:1,overshoot:20};
    const state={...defaults,...(readPreset("motion")||{})};let animations=[];
    shell(mount,{number:"02",title:"MOTION LAB",copy:"Timing is a design material. Play one motion or compare two responses side by side.",stageClass:"motion-stage",stage:'<div class="motion-lane"><div class="motion-object">CARD</div><div class="motion-compare" hidden><div class="motion-compare-row" data-side="left"><small>EASE OUT</small><div class="motion-object">A</div></div><div class="motion-compare-row" data-side="right"><small>SPRING</small><div class="motion-object">B</div></div></div><div class="motion-progress"></div></div>',controls:`
      <div class="lab-control-group"><span class="lab-control-title">OBJECT</span><div class="lab-segments" data-motion="shape">${["card","dot","panel","button"].map(v=>segment(v,v.toUpperCase(),v===state.shape)).join("")}</div><div class="lab-actions"><button class="lab-action primary" data-action="play" type="button">PLAY</button><button class="lab-action" data-action="compare" type="button">COMPARE MODE</button></div></div>
      <div class="lab-control-group"><span class="lab-control-title">PARAMETERS</span>${rangeField("motionDuration","DURATION",150,2200,state.duration,10," ms")}${rangeField("motionDelay","DELAY",0,700,state.delay,10," ms")}${rangeField("motionDistance","DISTANCE",80,620,state.distance,5," px")}${rangeField("motionScale","SCALE",.6,1.5,state.scale,.01,"×")}${rangeField("motionRotation","ROTATION",-180,180,state.rotation,1,"°")}${rangeField("motionOpacity","OPACITY",.1,1,state.opacity,.01)}</div>
      <div class="lab-control-group"><span class="lab-control-title">EASING</span><div class="lab-field"><label for="motionEasing">PRESET</label><select id="motionEasing">${Object.keys(easings).map(v=>`<option value="${v}">${v.toUpperCase()}</option>`).join("")}<option value="custom">CUSTOM BEZIER</option></select></div><div class="bezier-view"><svg viewBox="0 0 100 70" aria-label="Cubic bezier curve"><line x1="8" y1="62" x2="92" y2="8"></line><path id="motionCurve" d="M8 62 C 27 18, 33 8, 92 8"></path></svg><code id="motionBezier">cubic-bezier(.22,.65,.3,1)</code></div>${rangeField("motionX1","X1",0,1,state.x1,.01)}${rangeField("motionY1","Y1",-1,2,state.y1,.01)}${rangeField("motionX2","X2",0,1,state.x2,.01)}${rangeField("motionY2","Y2",-1,2,state.y2,.01)}</div>
      <div class="lab-control-group"><span class="lab-control-title">SPRING FEEL</span>${rangeField("motionStiffness","STIFFNESS",60,360,state.stiffness,5)}${rangeField("motionDamping","DAMPING",6,40,state.damping,1)}${rangeField("motionMass","MASS",.5,2,state.mass,.1)}${rangeField("motionOvershoot","OVERSHOOT",0,60,state.overshoot,1,"%")}</div>
      <div class="lab-control-group"><span class="lab-control-title">COMPARE</span><div class="lab-field-row"><select id="motionLeft">${Object.keys(easings).map(v=>`<option value="${v}">${v.toUpperCase()}</option>`).join("")}</select><select id="motionRight">${Object.keys(easings).map(v=>`<option value="${v}">${v.toUpperCase()}</option>`).join("")}</select></div></div>
      <div class="lab-control-group"><span class="lab-control-title">OUTPUT</span><pre class="lab-code" id="motionCode"></pre><div class="lab-actions"><button class="lab-action" data-action="copy" type="button">COPY CSS</button><button class="lab-action" data-action="save" type="button">SAVE PRESET</button><button class="lab-action" data-action="random" type="button">RANDOMIZE</button><button class="lab-action" data-action="reset" type="button">RESET</button></div></div>`});
    const object=$(mount,".motion-lane > .motion-object"),compare=$(mount,".motion-compare"),progress=$(mount,".motion-progress");
    const custom=()=>`cubic-bezier(${state.x1}, ${state.y1}, ${state.x2}, ${state.y2})`;
    const easing=key=>key==="custom"?custom():easings[key];
    const springFromControls=()=>{const energy=clamp((state.stiffness/(state.damping*state.mass))/12,0,1),over=clamp(state.overshoot/100,0,.6);return `cubic-bezier(${(.12+energy*.1).toFixed(2)}, ${(1+over).toFixed(2)}, ${(.28+state.damping/200).toFixed(2)}, 1)`};
    const update=()=>{object.dataset.shape=state.shape;object.textContent=state.shape.toUpperCase();compare.hidden=!state.compare;object.hidden=state.compare;$(mount,"#motionEasing").value=state.easing;$(mount,"#motionLeft").value=state.left;$(mount,"#motionRight").value=state.right;const code=`transition-property: transform, opacity;\ntransition-duration: ${state.duration}ms;\ntransition-delay: ${state.delay}ms;\ntransition-timing-function: ${state.easing==="spring"?springFromControls():easing(state.easing)};`;$(mount,"#motionCode").textContent=code;$(mount,"#motionBezier").textContent=custom();const path=$(mount,"#motionCurve"),x1=8+84*state.x1,y1=62-54*clamp(state.y1,0,1),x2=8+84*state.x2,y2=62-54*clamp(state.y2,0,1);path.setAttribute("d",`M8 62 C ${x1} ${y1}, ${x2} ${y2}, 92 8`);$$ (mount,"[data-motion='shape'] button").forEach(b=>b.classList.toggle("is-active",b.dataset.value===state.shape))};
    const cancel=()=>{animations.forEach(a=>a.cancel());animations=[];progress.style.width="0"};
    const playObject=(node,ease)=>{const lane=$(mount,".motion-lane"),max=Math.max(20,lane.clientWidth-node.offsetWidth-48),distance=Math.min(state.distance,max),frames=[{transform:"translateX(0) scale(1) rotate(0deg)",opacity:1},{transform:`translateX(${distance}px) scale(${state.scale}) rotate(${state.rotation}deg)`,opacity:state.opacity}];const animation=node.animate(frames,{duration:state.duration,delay:state.delay,easing:ease,fill:"both",direction:"alternate",iterations:2});animations.push(animation)};
    const play=()=>{cancel();if(state.compare){const left=$(compare,"[data-side='left']"),right=$(compare,"[data-side='right']");$(left,"small").textContent=state.left.toUpperCase();$(right,"small").textContent=state.right.toUpperCase();playObject($(left,".motion-object"),easing(state.left));playObject($(right,".motion-object"),easing(state.right))}else playObject(object,state.easing==="spring"?springFromControls():easing(state.easing));animations.push(progress.animate([{width:"0"},{width:"100%"}],{duration:(state.duration*2)+state.delay,easing:"linear",fill:"both"}));setCursorState("PLAY")};
    mount.addEventListener("input",event=>{const map={motionDuration:"duration",motionDelay:"delay",motionDistance:"distance",motionScale:"scale",motionRotation:"rotation",motionOpacity:"opacity",motionEasing:"easing",motionX1:"x1",motionY1:"y1",motionX2:"x2",motionY2:"y2",motionStiffness:"stiffness",motionDamping:"damping",motionMass:"mass",motionOvershoot:"overshoot",motionLeft:"left",motionRight:"right"},key=map[event.target.id];if(!key)return;state[key]=event.target.type==="range"?Number(event.target.value):event.target.value;if(["x1","y1","x2","y2"].includes(key))state.easing="custom";update()});
    $$ (mount,"[data-motion='shape'] button").forEach(button=>button.addEventListener("click",()=>{state.shape=button.dataset.value;update()}));
    mount.addEventListener("click",event=>{const action=event.target.dataset.action;if(!action)return;if(action==="play")play();if(action==="compare"){state.compare=!state.compare;event.target.classList.toggle("is-active",state.compare);update();play()}if(action==="copy")copyText($(mount,"#motionCode").textContent);if(action==="save")savePreset("motion",state);if(action==="random"){state.duration=300+Math.round(Math.random()*1200);state.distance=160+Math.round(Math.random()*360);state.rotation=Math.round(Math.random()*90-45);state.scale=Number((.8+Math.random()*.5).toFixed(2));state.easing=Object.keys(easings)[Math.floor(Math.random()*Object.keys(easings).length)];syncInputs();play()}if(action==="reset"){Object.assign(state,defaults);syncInputs();cancel()}});
    const syncInputs=()=>{const ids={motionDuration:"duration",motionDelay:"delay",motionDistance:"distance",motionScale:"scale",motionRotation:"rotation",motionOpacity:"opacity",motionX1:"x1",motionY1:"y1",motionX2:"x2",motionY2:"y2",motionStiffness:"stiffness",motionDamping:"damping",motionMass:"mass",motionOvershoot:"overshoot"};Object.entries(ids).forEach(([id,key])=>{$(mount,`#${id}`).value=state[key];$(mount,`[data-output='${id}']`).textContent=`${state[key]}${$(mount,`[data-output='${id}']`).textContent.replace(/^[-.\d]+/,"")}`});update()};
    syncInputs();requestAnimationFrame(play);return ()=>{cancel();setCursorState("")};
  }

  function createSpatialLab(mount){
    const layouts={hud:[[-.32,-.28,40],[.32,-.28,20],[-.3,.28,-45],[.3,.28,-20],[0,0,90]],menu:[[-.3,-.1,-30],[-.12,0,45],[.12,.08,70],[.34,.16,-25],[.05,-.28,10]],dashboard:[[-.3,-.2,0],[0,-.2,25],[.3,-.2,0],[-.18,.22,45],[.18,.22,45]],dialog:[[-.28,0,-60],[.28,0,-60],[0,0,100],[-.18,.3,-20],[.18,.3,-20]],game:[[-.32,-.28,25],[.32,-.28,25],[-.31,.27,-35],[.31,.27,-35],[0,.08,70]]};
    const names=["MENU","STATUS","OBJECT","INFO","ACTION"];
    const defaults={preset:"hud",selected:4,scale:1,rotate:0};
    const state={...defaults,panels:layouts.hud.map((p,i)=>({name:names[i],x:p[0],y:p[1],z:p[2],scale:1,rotate:0}))};
    shell(mount,{number:"03",title:"SPATIAL UI LAB",copy:"Arrange interface panels across simulated depth, comfort and focus without requiring WebXR.",stageClass:"spatial-stage",stage:'<div class="spatial-room"><div class="spatial-floor"></div><div class="comfort-zone"></div><div class="spatial-panels"></div></div>',controls:`
      <div class="lab-control-group"><span class="lab-control-title">SPATIAL PRESET</span><div class="lab-segments" data-spatial="preset">${Object.keys(layouts).map(v=>segment(v,v.toUpperCase().replace("MENU","FLOATING MENU"),v==="hud")).join("")}</div></div>
      <div class="lab-control-group"><span class="lab-control-title">SELECTED PANEL</span><div class="lab-field"><label for="spatialPanel">PANEL</label><select id="spatialPanel">${names.map((v,i)=>`<option value="${i}">${v}</option>`).join("")}</select></div>${rangeField("spatialX","MOVE X",-50,50,0,1,"%")}${rangeField("spatialY","MOVE Y",-45,45,0,1,"%")}${rangeField("spatialDepth","DEPTH",-140,140,90,1)}${rangeField("spatialScale","SCALE",.65,1.35,1,.01,"×")}${rangeField("spatialRotate","ROTATE",-35,35,0,1,"°")}</div>
      <div class="lab-control-group"><span class="lab-control-title">FOCUS + SPACE</span><div class="lab-actions"><button class="lab-action teal" data-action="focus" type="button">FOCUS MODE</button><button class="lab-action" data-action="random" type="button">RANDOMIZE SPACE</button><button class="lab-action" data-action="reset" type="button">RESET</button></div></div>`});
    const stage=$(mount,".spatial-stage"),room=$(mount,".spatial-room"),container=$(mount,".spatial-panels"),controller=new AbortController();let focus=false,drag=null,frame=0;
    const selected=()=>state.panels[state.selected];
    const render=()=>{
      container.innerHTML=state.panels.map((panel,i)=>`<button class="spatial-panel${i===state.selected?" is-selected":""}${focus&&i===state.selected?" is-focused":""}" type="button" data-panel="${i}" aria-label="${panel.name} spatial panel"><small>Z ${Math.round(panel.z)}</small><strong>${panel.name}</strong></button>`).join("");
      room.classList.toggle("has-focus",focus);
      $$ (container,".spatial-panel").forEach((node,i)=>{const panel=state.panels[i],w=stage.clientWidth||800,h=stage.clientHeight||600,inside=Math.abs(panel.x)<=.25&&Math.abs(panel.y)<=.24,isFocus=focus&&i===state.selected,displayZ=panel.z+(isFocus?80:0),depthScale=1+displayZ/800;node.style.setProperty("--x",`${panel.x*w}px`);node.style.setProperty("--y",`${panel.y*h}px`);node.style.setProperty("--z",`${displayZ}px`);node.style.setProperty("--scale",panel.scale*depthScale*(isFocus?1.08:1));node.style.setProperty("--rotate",`${panel.rotate}deg`);node.style.setProperty("--depth-shadow",`${Math.max(0,displayZ/8)}px`);node.style.setProperty("--depth-blur",`${Math.max(4,10-displayZ/35)}px`);node.style.opacity=String(clamp(.82+displayZ/500,.58,1));node.classList.toggle("is-warning",!inside)});
    };
    const sync=()=>{const panel=selected(),pairs={spatialX:Math.round(panel.x*100),spatialY:Math.round(panel.y*100),spatialDepth:panel.z,spatialScale:panel.scale,spatialRotate:panel.rotate};Object.entries(pairs).forEach(([id,value])=>{const input=$(mount,`#${id}`);input.value=value;const output=$(mount,`[data-output='${id}']`),suffix=output.textContent.replace(/^[-.\d]+/,"");output.textContent=`${value}${suffix}`});$(mount,"#spatialPanel").value=state.selected;render()};
    const applyLayout=(name)=>{state.preset=name;state.panels=layouts[name].map((p,i)=>({name:names[i],x:p[0],y:p[1],z:p[2],scale:1,rotate:0}));focus=false;$$ (mount,"[data-spatial] button").forEach(b=>b.classList.toggle("is-active",b.dataset.value===name));sync()};
    container.addEventListener("pointerdown",event=>{const node=event.target.closest(".spatial-panel");if(!node)return;state.selected=Number(node.dataset.panel);const p=selected();drag={id:event.pointerId,startX:event.clientX,startY:event.clientY,x:p.x,y:p.y};node.setPointerCapture(event.pointerId);setCursorState("GRAB");sync()},{signal:controller.signal});
    container.addEventListener("pointermove",event=>{if(!drag||drag.id!==event.pointerId)return;const p=selected();p.x=clamp(drag.x+(event.clientX-drag.startX)/stage.clientWidth,-.48,.48);p.y=clamp(drag.y+(event.clientY-drag.startY)/stage.clientHeight,-.44,.44);sync()},{signal:controller.signal});
    const stopDrag=()=>{drag=null;setCursorState("DEPTH")};container.addEventListener("pointerup",stopDrag,{signal:controller.signal});container.addEventListener("pointercancel",stopDrag,{signal:controller.signal});
    stage.addEventListener("pointermove",event=>{if(drag||reduce)return;const r=stage.getBoundingClientRect(),x=(event.clientX-r.left)/r.width-.5,y=(event.clientY-r.top)/r.height-.5;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{room.style.transform=`rotateX(${-y*2.5}deg) rotateY(${x*3.5}deg)`})},{signal:controller.signal});
    stage.addEventListener("pointerleave",()=>{room.style.transform=""},{signal:controller.signal});
    mount.addEventListener("input",event=>{if(event.target.id==="spatialPanel"){state.selected=Number(event.target.value);sync();return}const map={spatialX:"x",spatialY:"y",spatialDepth:"z",spatialScale:"scale",spatialRotate:"rotate"},key=map[event.target.id];if(!key)return;let value=Number(event.target.value);if(key==="x"||key==="y")value/=100;selected()[key]=value;render()},{signal:controller.signal});
    $$ (mount,"[data-spatial] button").forEach(button=>button.addEventListener("click",()=>applyLayout(button.dataset.value),{signal:controller.signal}));
    mount.addEventListener("click",event=>{const action=event.target.dataset.action;if(action==="focus"){focus=!focus;event.target.classList.toggle("is-active",focus);render()}if(action==="random"){state.panels.forEach(panel=>{panel.x=Number((Math.random()*.72-.36).toFixed(2));panel.y=Number((Math.random()*.58-.29).toFixed(2));panel.z=Math.round(Math.random()*220-100);panel.rotate=Math.round(Math.random()*24-12)});focus=false;sync()}if(action==="reset")applyLayout("hud")},{signal:controller.signal});
    setCursorState("DEPTH");requestAnimationFrame(()=>applyLayout("hud"));return ()=>{controller.abort();cancelAnimationFrame(frame);setCursorState("")};
  }

  function createInteractionLab(mount){
    const modes=["magnetic","tilt","follow","drag","spring","repulse","trail"],defaults={mode:"magnetic",mode2:"repulse",split:false,strength:.24,radius:220,lag:.12,friction:.84};
    const state={...defaults},objects=[{x:0,y:0,vx:0,vy:0},{x:180,y:0,vx:0,vy:0}],pointer={x:0,y:0,inside:false,down:false},controller=new AbortController();let raf=0,lastTrail=0,dragIndex=-1;
    shell(mount,{number:"04",title:"INTERACTION PLAYGROUND",copy:"Keep the object constant and compare how different input models change its character.",stageClass:"interaction-stage",stage:'<div class="interaction-zone"><div class="interaction-divider"></div><div class="interaction-object" data-object="0">MAGNETIC</div><div class="interaction-object is-secondary" data-object="1">REPULSE</div></div>',controls:`
      <div class="lab-control-group"><span class="lab-control-title">INTERACTION MODEL</span><div class="lab-segments" data-interaction="mode">${modes.map(v=>segment(v,v==="spring"?"SPRING DRAG":v.toUpperCase(),v===state.mode)).join("")}</div><div class="lab-actions"><button class="lab-action" data-action="split" type="button">SPLIT MODE</button></div></div>
      <div class="lab-control-group"><span class="lab-control-title">FEEL</span>${rangeField("interactionStrength","STRENGTH",.04,.7,state.strength,.01)}${rangeField("interactionRadius","RADIUS",80,380,state.radius,5," px")}${rangeField("interactionLag","LAG / SPRING",.03,.35,state.lag,.01)}${rangeField("interactionFriction","FRICTION",.6,.98,state.friction,.01)}</div>
      <div class="lab-control-group"><span class="lab-control-title">COMPARE WITH</span><div class="lab-field"><select id="interactionMode2">${modes.map(v=>`<option value="${v}">${v.toUpperCase()}</option>`).join("")}</select></div></div>
      <div class="lab-control-group"><div class="lab-actions"><button class="lab-action primary" data-action="reset" type="button">RESET</button></div></div>`});
    const zone=$(mount,".interaction-zone"),nodes=$$(zone,".interaction-object");
    const center=()=>({x:zone.clientWidth/2,y:zone.clientHeight/2});
    const reset=()=>{objects[0]={x:state.split?-zone.clientWidth*.24:0,y:0,vx:0,vy:0,rx:0,ry:0};objects[1]={x:zone.clientWidth*.24,y:0,vx:0,vy:0,rx:0,ry:0};pointer.inside=false;render()};
    const modeFor=i=>i===0?state.mode:state.mode2;
    const render=()=>{zone.classList.toggle("is-split",state.split);nodes.forEach((node,i)=>{node.textContent=(modeFor(i)==="spring"?"SPRING DRAG":modeFor(i)).toUpperCase();node.style.transform=`translate(calc(-50% + ${objects[i].x}px),calc(-50% + ${objects[i].y}px)) rotateX(${objects[i].rx||0}deg) rotateY(${objects[i].ry||0}deg)`;});$$ (mount,"[data-interaction='mode'] button").forEach(b=>b.classList.toggle("is-active",b.dataset.value===state.mode));$(mount,"#interactionMode2").value=state.mode2};
    const localPoint=event=>{const r=zone.getBoundingClientRect();return{x:event.clientX-r.left,y:event.clientY-r.top}};
    const applyTilt=(node,point,index)=>{const r=node.getBoundingClientRect(),x=(point.x-(r.left-zone.getBoundingClientRect().left+r.width/2))/r.width,y=(point.y-(r.top-zone.getBoundingClientRect().top+r.height/2))/r.height;objects[index].rx=-y*16;objects[index].ry=x*18};
    const step=()=>{const c=center();objects.forEach((obj,i)=>{if(i===1&&!state.split)return;const mode=modeFor(i),baseX=state.split?(i===1?zone.clientWidth*.24:-zone.clientWidth*.24):0,targetX=pointer.x-c.x,targetY=pointer.y-c.y,dx=targetX-obj.x,dy=targetY-obj.y,dist=Math.hypot(dx,dy)||1;if(mode==="follow"&&pointer.inside){obj.vx+=dx*state.lag*.08;obj.vy+=dy*state.lag*.08}else if(mode==="magnetic"&&pointer.inside&&dist<state.radius){obj.vx+=dx*state.strength*.035;obj.vy+=dy*state.strength*.035}else if(mode==="repulse"&&pointer.inside&&dist<state.radius){obj.vx-=dx/dist*(state.radius-dist)*state.strength*.018;obj.vy-=dy/dist*(state.radius-dist)*state.strength*.018}else if(mode==="spring"&&pointer.down&&dragIndex===i){obj.vx+=dx*state.lag*.12;obj.vy+=dy*state.lag*.12}else if(!pointer.down||dragIndex!==i){obj.vx+=(baseX-obj.x)*.025;obj.vy+=(0-obj.y)*.025}obj.vx*=state.friction;obj.vy*=state.friction;obj.x=clamp(obj.x+obj.vx,-zone.clientWidth*.43,zone.clientWidth*.43);obj.y=clamp(obj.y+obj.vy,-zone.clientHeight*.4,zone.clientHeight*.4);nodes[i].style.transform=`translate(calc(-50% + ${obj.x}px),calc(-50% + ${obj.y}px)) rotateX(${obj.rx||0}deg) rotateY(${obj.ry||0}deg)`;});raf=requestAnimationFrame(step)};
    zone.addEventListener("pointermove",event=>{const p=localPoint(event);pointer.x=p.x;pointer.y=p.y;pointer.inside=true;nodes.forEach((node,i)=>{if((modeFor(i)==="drag"||modeFor(i)==="spring")&&pointer.down&&dragIndex===i&&modeFor(i)==="drag"){const c=center(),nextX=clamp(p.x-c.x,-zone.clientWidth*.43,zone.clientWidth*.43),nextY=clamp(p.y-c.y,-zone.clientHeight*.4,zone.clientHeight*.4);objects[i].vx=nextX-objects[i].x;objects[i].vy=nextY-objects[i].y;objects[i].x=nextX;objects[i].y=nextY}if(modeFor(i)==="tilt")applyTilt(node,p,i);if(modeFor(i)==="trail"&&performance.now()-lastTrail>45){lastTrail=performance.now();const dot=document.createElement("i");dot.className="trail-dot";dot.style.left=`${p.x}px`;dot.style.top=`${p.y}px`;zone.append(dot);setTimeout(()=>dot.remove(),600)}})},{signal:controller.signal});
    zone.addEventListener("pointerleave",()=>{pointer.inside=false;objects.forEach(obj=>{obj.rx=0;obj.ry=0});render()},{signal:controller.signal});
    nodes.forEach((node,i)=>node.addEventListener("pointerdown",event=>{pointer.down=true;dragIndex=i;node.setPointerCapture(event.pointerId);setCursorState("GRAB")},{signal:controller.signal}));
    const release=()=>{pointer.down=false;dragIndex=-1;setCursorState("TEST")};zone.addEventListener("pointerup",release,{signal:controller.signal});zone.addEventListener("pointercancel",release,{signal:controller.signal});
    mount.addEventListener("input",event=>{const map={interactionStrength:"strength",interactionRadius:"radius",interactionLag:"lag",interactionFriction:"friction",interactionMode2:"mode2"},key=map[event.target.id];if(!key)return;state[key]=event.target.type==="range"?Number(event.target.value):event.target.value;render()},{signal:controller.signal});
    $$ (mount,"[data-interaction] button").forEach(button=>button.addEventListener("click",()=>{state.mode=button.dataset.value;reset()},{signal:controller.signal}));
    mount.addEventListener("click",event=>{if(event.target.dataset.action==="split"){state.split=!state.split;event.target.classList.toggle("is-active",state.split);reset()}if(event.target.dataset.action==="reset")reset()},{signal:controller.signal});
    setCursorState("TEST");reset();raf=requestAnimationFrame(step);return ()=>{controller.abort();cancelAnimationFrame(raf);setCursorState("")};
  }

  function createMaterialLab(mount){
    const presets={soft:{a:"#ffb8dc",b:"#9be9e6",angle:135,blur:22,opacity:.24,saturation:135,brightness:105,borderOpacity:.65,noise:.06,glow:"#916cff",intensity:.25,radius:38,spread:0,shadowX:0,shadowY:28,shadowBlur:70,shadowOpacity:.22,borderWidth:1,corner:28},neon:{a:"#24173f",b:"#123b47",angle:120,blur:14,opacity:.18,saturation:170,brightness:112,borderOpacity:.72,noise:.08,glow:"#ff62b0",intensity:.52,radius:54,spread:4,shadowX:0,shadowY:30,shadowBlur:80,shadowOpacity:.35,borderWidth:1,corner:22},frost:{a:"#dff5ff",b:"#f7dcea",angle:150,blur:34,opacity:.42,saturation:110,brightness:112,borderOpacity:.82,noise:.1,glow:"#ffffff",intensity:.3,radius:44,spread:0,shadowX:0,shadowY:20,shadowBlur:55,shadowOpacity:.16,borderWidth:1,corner:32},dark:{a:"#17142d",b:"#24515a",angle:135,blur:26,opacity:.14,saturation:145,brightness:88,borderOpacity:.32,noise:.07,glow:"#00bdb6",intensity:.38,radius:52,spread:1,shadowX:0,shadowY:34,shadowBlur:84,shadowOpacity:.48,borderWidth:1,corner:18},holo:{a:"#ff89c7",b:"#73ece4",angle:115,blur:18,opacity:.22,saturation:180,brightness:118,borderOpacity:.72,noise:.05,glow:"#916cff",intensity:.45,radius:64,spread:2,shadowX:0,shadowY:28,shadowBlur:72,shadowOpacity:.28,borderWidth:1,corner:36},minimal:{a:"#edf6f6",b:"#fff0f7",angle:145,blur:10,opacity:.56,saturation:100,brightness:105,borderOpacity:.9,noise:0,glow:"#ffffff",intensity:0,radius:0,spread:0,shadowX:0,shadowY:16,shadowBlur:36,shadowOpacity:.12,borderWidth:1,corner:12}};
    const state={...presets.soft,...(readPreset("material")||{}),object:"card"};
    shell(mount,{number:"05",title:"MATERIAL LAB",copy:"Tune a digital surface through glass, light, border and shadow instead of color alone.",stageClass:"material-stage",stage:'<div class="material-object" data-object="card"><small>DIGITAL MATERIAL</small><strong>SOFT<br>GLASS</strong><p>Move the pointer to shift the light source.</p></div>',controls:`
      <div class="lab-control-group"><span class="lab-control-title">OBJECT</span><div class="lab-segments" data-material="object">${["card","panel","button","badge"].map(v=>segment(v,v.toUpperCase(),v==="card")).join("")}</div></div>
      <div class="lab-control-group"><span class="lab-control-title">PRESETS</span><div class="lab-segments" data-material="preset">${Object.keys(presets).map(v=>segment(v,v.toUpperCase().replace("DARK","DARK XR").replace("HOLO","HOLOGRAPHIC"),v==="soft")).join("")}</div></div>
      <div class="lab-control-group"><span class="lab-control-title">BACKGROUND</span><div class="lab-field-row"><input id="materialA" type="color" value="${state.a}" aria-label="Background color A"><input id="materialB" type="color" value="${state.b}" aria-label="Background color B"><input id="materialGlow" type="color" value="${state.glow}" aria-label="Glow color"></div>${rangeField("materialAngle","GRADIENT ANGLE",0,360,state.angle,1,"°")}</div>
      <div class="lab-control-group"><span class="lab-control-title">GLASS</span>${rangeField("materialBlur","BLUR",0,50,state.blur,1," px")}${rangeField("materialOpacity","OPACITY",.05,.75,state.opacity,.01)}${rangeField("materialSaturation","SATURATION",80,220,state.saturation,1,"%")}${rangeField("materialBrightness","BRIGHTNESS",70,140,state.brightness,1,"%")}${rangeField("materialNoise","NOISE",0,.2,state.noise,.01)}</div>
      <div class="lab-control-group"><span class="lab-control-title">GLOW + SHADOW</span>${rangeField("materialIntensity","GLOW INTENSITY",0,.8,state.intensity,.01)}${rangeField("materialRadius","GLOW RADIUS",0,100,state.radius,1," px")}${rangeField("materialShadowY","SHADOW Y",-20,60,state.shadowY,1," px")}${rangeField("materialShadowBlur","SHADOW BLUR",0,120,state.shadowBlur,1," px")}${rangeField("materialShadowOpacity","SHADOW OPACITY",0,.7,state.shadowOpacity,.01)}</div>
      <div class="lab-control-group"><span class="lab-control-title">BORDER</span>${rangeField("materialBorderWidth","WIDTH",0,5,state.borderWidth,1," px")}${rangeField("materialCorner","RADIUS",0,60,state.corner,1," px")}${rangeField("materialBorderOpacity","OPACITY",0,1,state.borderOpacity,.01)}</div>
      <div class="lab-control-group"><span class="lab-control-title">OUTPUT</span><pre class="lab-code" id="materialCode"></pre><div class="lab-actions"><button class="lab-action" data-action="copy" type="button">COPY CSS</button><button class="lab-action" data-action="save" type="button">SAVE PRESET</button><button class="lab-action" data-action="random" type="button">RANDOMIZE</button><button class="lab-action" data-action="reset" type="button">RESET</button></div></div>`});
    const stage=$(mount,".material-stage"),object=$(mount,".material-object"),controller=new AbortController();
    const css=()=>`background: rgba(255,255,255,${state.opacity});\nbackdrop-filter: blur(${state.blur}px) saturate(${state.saturation}%) brightness(${state.brightness}%);\nborder: ${state.borderWidth}px solid rgba(255,255,255,${state.borderOpacity});\nborder-radius: ${state.corner}px;\nbox-shadow: ${state.shadowX}px ${state.shadowY}px ${state.shadowBlur}px rgba(42,26,74,${state.shadowOpacity}), 0 0 ${state.radius}px ${state.glow}${Math.round(state.intensity*255).toString(16).padStart(2,"0")};`;
    const update=()=>{stage.style.setProperty("--material-a",state.a);stage.style.setProperty("--material-b",state.b);stage.style.setProperty("--material-angle",`${state.angle}deg`);object.dataset.object=state.object;object.style.setProperty("--glass-blur",`${state.blur}px`);object.style.setProperty("--glass-opacity",state.opacity);object.style.setProperty("--glass-saturation",`${state.saturation}%`);object.style.setProperty("--glass-brightness",`${state.brightness}%`);object.style.setProperty("--border-opacity",state.borderOpacity);object.style.setProperty("--noise-opacity",state.noise);object.style.setProperty("--glow-color",`${state.glow}${Math.round(state.intensity*255).toString(16).padStart(2,"0")}`);object.style.setProperty("--glow-radius",`${state.radius}px`);object.style.setProperty("--glow-spread",`${state.spread}px`);object.style.setProperty("--shadow-x",`${state.shadowX}px`);object.style.setProperty("--shadow-y",`${state.shadowY}px`);object.style.setProperty("--shadow-blur",`${state.shadowBlur}px`);object.style.setProperty("--shadow-opacity",state.shadowOpacity);object.style.setProperty("--border-width",`${state.borderWidth}px`);object.style.setProperty("--material-radius",`${state.corner}px`);$(mount,"#materialCode").textContent=css();$$ (mount,"[data-material='object'] button").forEach(b=>b.classList.toggle("is-active",b.dataset.value===state.object))};
    const sync=()=>{const ids={materialA:"a",materialB:"b",materialGlow:"glow",materialAngle:"angle",materialBlur:"blur",materialOpacity:"opacity",materialSaturation:"saturation",materialBrightness:"brightness",materialNoise:"noise",materialIntensity:"intensity",materialRadius:"radius",materialShadowY:"shadowY",materialShadowBlur:"shadowBlur",materialShadowOpacity:"shadowOpacity",materialBorderWidth:"borderWidth",materialCorner:"corner",materialBorderOpacity:"borderOpacity"};Object.entries(ids).forEach(([id,key])=>{const input=$(mount,`#${id}`);input.value=state[key];const output=$(mount,`[data-output='${id}']`);if(output){const suffix=output.textContent.replace(/^[-.\d]+/,"");output.textContent=`${state[key]}${suffix}`}});update()};
    mount.addEventListener("input",event=>{const map={materialA:"a",materialB:"b",materialGlow:"glow",materialAngle:"angle",materialBlur:"blur",materialOpacity:"opacity",materialSaturation:"saturation",materialBrightness:"brightness",materialNoise:"noise",materialIntensity:"intensity",materialRadius:"radius",materialShadowY:"shadowY",materialShadowBlur:"shadowBlur",materialShadowOpacity:"shadowOpacity",materialBorderWidth:"borderWidth",materialCorner:"corner",materialBorderOpacity:"borderOpacity"},key=map[event.target.id];if(!key)return;state[key]=event.target.type==="range"?Number(event.target.value):event.target.value;update()},{signal:controller.signal});
    $$ (mount,"[data-material='object'] button").forEach(button=>button.addEventListener("click",()=>{state.object=button.dataset.value;update()},{signal:controller.signal}));$$ (mount,"[data-material='preset'] button").forEach(button=>button.addEventListener("click",()=>{Object.assign(state,presets[button.dataset.value]);$$ (mount,"[data-material='preset'] button").forEach(b=>b.classList.toggle("is-active",b===button));sync()},{signal:controller.signal}));
    stage.addEventListener("pointermove",event=>{const r=stage.getBoundingClientRect(),x=(event.clientX-r.left)/r.width*100,y=(event.clientY-r.top)/r.height*100;stage.style.setProperty("--light-x",`${x}%`);stage.style.setProperty("--light-y",`${y}%`);object.style.setProperty("--light-x",`${x}%`);object.style.setProperty("--light-y",`${y}%`)},{signal:controller.signal});
    mount.addEventListener("click",event=>{const action=event.target.dataset.action;if(action==="copy")copyText(css());if(action==="save")savePreset("material",state);if(action==="reset"){Object.assign(state,presets.soft,{object:"card"});sync()}if(action==="random"){state.angle=Math.round(Math.random()*360);state.blur=Math.round(8+Math.random()*34);state.opacity=Number((.12+Math.random()*.42).toFixed(2));state.radius=Math.round(Math.random()*80);state.corner=Math.round(8+Math.random()*44);sync()}},{signal:controller.signal});
    sync();return ()=>controller.abort();
  }

  function createGenerativeLab(mount){
    const mobile=matchMedia("(max-width:800px)").matches,maxCount=mobile?60:120,defaults={mode:"particle",count:mobile?42:78,speed:1,gravity:.08,force:.28,trail:.16,chaos:.35};
    const state={...defaults,polarity:1},controller=new AbortController();let particles=[],ripples=[],raf=0,ctx,canvas,resizeObserver,pointer={x:0,y:0,inside:false,down:false},dpr=1;
    shell(mount,{number:"06",title:"GENERATIVE PLAYGROUND",copy:"A restrained creative-coding field where pointer input changes a visible system, not just an effect.",stageClass:"generative-stage",stage:'<canvas id="generativeCanvas" aria-label="Interactive generative canvas"></canvas><span class="generative-hint">MOVE / TOUCH TO GUIDE · CLICK TO SEED</span>',controls:`
      <div class="lab-control-group"><span class="lab-control-title">SYSTEM</span><div class="lab-segments" data-generative="mode">${[["particle","PARTICLE FIELD"],["gravity","GRAVITY GARDEN"],["flow","FLOW FIELD"],["orbit","ORBIT"],["ripple","RIPPLE"]].map(([v,l])=>segment(v,l,v===state.mode)).join("")}</div></div>
      <div class="lab-control-group"><span class="lab-control-title">BEHAVIOR</span><button class="lab-action" data-action="polarity" type="button">POINTER · ATTRACT</button>${rangeField("generativeCount","COUNT",20,maxCount,state.count,1)}${rangeField("generativeSpeed","SPEED",.2,2.4,state.speed,.1)}${rangeField("generativeGravity","GRAVITY",-.2,.3,state.gravity,.01)}${rangeField("generativeForce","FORCE",.02,.8,state.force,.01)}${rangeField("generativeTrail","TRAIL",.03,.4,state.trail,.01)}${rangeField("generativeChaos","CHAOS",0,1,state.chaos,.01)}</div>
      <div class="lab-control-group"><div class="lab-actions"><button class="lab-action teal" data-action="random" type="button">RANDOMIZE</button><button class="lab-action" data-action="clear" type="button">CLEAR</button><button class="lab-action" data-action="reset" type="button">RESET</button></div></div>`});
    canvas=$(mount,"#generativeCanvas");ctx=canvas.getContext("2d");
    const resize=()=>{const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*dpr));canvas.height=Math.max(1,Math.round(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0)};
    const seed=()=>{const r=canvas.getBoundingClientRect();particles=Array.from({length:Math.min(state.count,maxCount)},(_,i)=>({x:Math.random()*r.width,y:Math.random()*r.height,vx:(Math.random()-.5)*1.5,vy:(Math.random()-.5)*1.5,size:1.2+Math.random()*3.4,hue:i%3,phase:Math.random()*Math.PI*2,growth:.4+Math.random()}))};
    const point=event=>{const r=canvas.getBoundingClientRect();return{x:event.clientX-r.left,y:event.clientY-r.top}};
    const draw=()=>{const r=canvas.getBoundingClientRect(),w=r.width,h=r.height;ctx.fillStyle=`rgba(27,22,54,${state.trail})`;ctx.fillRect(0,0,w,h);const time=performance.now()*.001;particles.slice(0,state.count).forEach((p,i)=>{const dx=pointer.x-p.x,dy=pointer.y-p.y,dist=Math.hypot(dx,dy)||1;if(state.mode==="particle"&&pointer.inside&&dist<220){p.vx+=dx/dist*state.force*state.polarity;p.vy+=dy/dist*state.force*state.polarity}if(state.mode==="gravity"){p.vy+=state.gravity;p.vx+=Math.sin(time+p.phase)*.015*(1+state.chaos);p.size=Math.min(7,p.size+p.growth*.004)}if(state.mode==="flow"){const angle=Math.sin(p.x*.012+time)*2+Math.cos(p.y*.009-time)*state.chaos;p.vx+=Math.cos(angle)*state.force*.09;p.vy+=Math.sin(angle)*state.force*.09}if(state.mode==="orbit"){const cx=pointer.inside?pointer.x:w/2,cy=pointer.inside?pointer.y:h/2,angle=Math.atan2(p.y-cy,p.x-cx)+Math.PI/2;p.vx+=Math.cos(angle)*state.force*.16;p.vy+=Math.sin(angle)*state.force*.16+(Math.hypot(p.x-cx,p.y-cy)-130)*-.0008}if(state.mode==="ripple"){ripples.forEach(ring=>{const d=Math.hypot(p.x-ring.x,p.y-ring.y);if(Math.abs(d-ring.radius)<24){p.vx+=(p.x-ring.x)/(d||1)*state.force*.5;p.vy+=(p.y-ring.y)/(d||1)*state.force*.5}})}p.vx+=(Math.random()-.5)*state.chaos*.025;p.vy+=(Math.random()-.5)*state.chaos*.025;p.vx*=.985;p.vy*=.985;p.x+=p.vx*state.speed;p.y+=p.vy*state.speed;if(p.x<0)p.x=w;if(p.x>w)p.x=0;if(p.y<0)p.y=h;if(p.y>h)p.y=0;ctx.fillStyle=p.hue===0?"#ff78bd":p.hue===1?"#9f84ff":"#46ded5";ctx.globalAlpha=.72;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()});ripples=ripples.filter(ring=>ring.alpha>.02);ripples.forEach(ring=>{ring.radius+=2.2*state.speed;ring.alpha*=.97;ctx.strokeStyle=`rgba(106,235,226,${ring.alpha})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(ring.x,ring.y,ring.radius,0,Math.PI*2);ctx.stroke()});ctx.globalAlpha=1;raf=requestAnimationFrame(draw)};
    canvas.addEventListener("pointermove",event=>{Object.assign(pointer,point(event),{inside:true})},{signal:controller.signal});canvas.addEventListener("pointerleave",()=>pointer.inside=false,{signal:controller.signal});canvas.addEventListener("pointerdown",event=>{Object.assign(pointer,point(event),{inside:true,down:true});ripples.push({x:pointer.x,y:pointer.y,radius:4,alpha:.8});if(state.mode==="gravity"){for(let i=0;i<6&&particles.length<maxCount;i++)particles.push({x:pointer.x+(Math.random()-.5)*25,y:pointer.y+(Math.random()-.5)*25,vx:(Math.random()-.5),vy:-Math.random()*2,size:2,hue:i%3,phase:Math.random()*6,growth:1})}},{signal:controller.signal});canvas.addEventListener("pointerup",()=>pointer.down=false,{signal:controller.signal});
    mount.addEventListener("input",event=>{const map={generativeCount:"count",generativeSpeed:"speed",generativeGravity:"gravity",generativeForce:"force",generativeTrail:"trail",generativeChaos:"chaos"},key=map[event.target.id];if(!key)return;state[key]=Number(event.target.value);if(key==="count"&&particles.length<state.count)seed()},{signal:controller.signal});$$ (mount,"[data-generative] button").forEach(button=>button.addEventListener("click",()=>{state.mode=button.dataset.value;$$ (mount,"[data-generative] button").forEach(b=>b.classList.toggle("is-active",b===button));ripples=[]},{signal:controller.signal}));
    mount.addEventListener("click",event=>{const action=event.target.dataset.action;if(action==="polarity"){state.polarity*=-1;event.target.textContent=`POINTER · ${state.polarity>0?"ATTRACT":"REPEL"}`}if(action==="clear"){particles=[];ripples=[];ctx.clearRect(0,0,canvas.width,canvas.height)}if(action==="random"){state.chaos=Number(Math.random().toFixed(2));state.force=Number((.08+Math.random()*.6).toFixed(2));state.speed=Number((.4+Math.random()*1.6).toFixed(1));seed();toast("SYSTEM SHUFFLED")}if(action==="reset"){Object.assign(state,defaults,{polarity:1});const polarity=$(mount,"[data-action='polarity']");polarity.textContent="POINTER · ATTRACT";seed();toast("RESET")}}, {signal:controller.signal});
    resizeObserver=new ResizeObserver(()=>{resize();if(!particles.length)seed()});resizeObserver.observe(canvas);resize();seed();raf=requestAnimationFrame(draw);return ()=>{controller.abort();cancelAnimationFrame(raf);resizeObserver.disconnect();particles=[];ripples=[]};
  }

  const factories={image:createImageLab,motion:createMotionLab,spatial:createSpatialLab,interaction:createInteractionLab,material:createMaterialLab,generative:createGenerativeLab};
  let activeId="",cleanup=()=>{},labScroll=0;
  const activate=route=>{
    if(route==="lab"){if(activeId){cleanup();cleanup=()=>{};activeId=""}requestAnimationFrame(()=>{if(labScroll)scrollTo(0,labScroll)});return}
    const lab=LABS.find(item=>item.route===route);
    if(!lab){if(activeId){cleanup();cleanup=()=>{};activeId=""}return}
    if(activeId===lab.id)return;
    if(activeId)cleanup();
    activeId=lab.id;
    const mount=document.getElementById(`lab-${lab.id}-mount`);
    cleanup=factories[lab.id](mount)||(()=>{});
  };
  document.addEventListener("click",event=>{if(event.target.closest(".lab-card"))labScroll=scrollY},true);
  addEventListener("keydown",event=>{if(event.key==="Escape"&&document.body.dataset.page?.startsWith("lab-")){history.pushState({route:"lab"},"","#lab");showRoute("lab",false)}});
  addEventListener("portfolio:routechange",event=>activate(event.detail.route));
  renderIndex();
  activate(document.body.dataset.page||"about");
  window.LabRegistry=Object.freeze(LABS.map(lab=>Object.freeze({...lab})));
})();
